name: Deploy no Kubernetes
on:
    workflow_call: 
        inputs:
          environment-name:
            type: string
            required: true
          environment-url:
            type: string
            required: true
jobs:
    deploy:
        name: "Deploy"        
        runs-on: ubuntu-latest
        environment: 
            name: ${{ inputs.environment-name }}
            url: ${{ inputs.environment-url }}
        steps:
          - uses: actions/checkout@v4
          - uses: azure/k8s-set-context@v4
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.K8S_CONFIG }}
    
          - name: Update deployment
            run: "sed -i 's/host: homologacao.fabricioveronez.com/host: ${{ vars.BASE_URL }}/g' k8s/deployment.yaml"
          
          - uses: Azure/k8s-deploy@v5
            with:
                namespace: ${{ secrets.K8S_NAMESPACE }}
                manifests: |
                  k8s/deployment.yaml
                images: 'fabricioveronez/rv-teste:v${{ github.run_number }}'