name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - working-directory: ./src/
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    permissions:
        security-events: write
        actions: read
        contents: read
    uses: veronez-dev/desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit

  release:
    name: Criação da Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - uses: actions/checkout@v4
      - name: Analise do Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            fabricioveronez/rv-teste:v${{ github.run_number }}
            fabricioveronez/rv-teste:latest
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile

  deploy:
    name: "Deploy"     
    needs: [release]   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - uses: Azure/k8s-deploy@v5
        with:
            manifests: |
              k8s/deployment.yaml
            images: 'fabricioveronez/rv-teste:v${{ github.run_number }}'