name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - working-directory: ./src/
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: veronez-dev/desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit

  release:
    name: Criação da Release
    runs-on: ubuntu-latest
    needs: [testes]
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            fabricioveronez/rv-teste:v${{ github.run_number }}
            fabricioveronez/rv-teste:latest
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'image'
          image-ref: 'fabricioveronez/rv-teste:v${{ github.run_number }}'
          format: sarif
          output: 'trivy-docker-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - name: Upload Trivy scan results Docker
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: docker-result
          sarif_file: 'trivy-docker-results.sarif'

  deploy-homolog:
    needs: [release]
    uses: veronez-dev/desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment-name: homologacao
      environment-url: http://homologacao.fabricioveronez.com
    
      
  teste-e2e:
    name: Teste End to End
    runs-on: ubuntu-latest
    needs: [deploy-homolog]
    environment: 
      name: homologacao
    container:
      image: fabricioveronez/webdriver-dotnet:chrome
      env:
        BASE_URL: "http://${{ vars.BASE_URL }}"
    steps:
      - uses: actions/checkout@v4
      - working-directory: ./src/
        run: dotnet test ./Review-Filmes.Test.EndToEnd/Review-Filmes.Test.EndToEnd.csproj

  deploy-producao:
    needs: [teste-e2e]
    uses: veronez-dev/desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment-name: producao
      environment-url: http://producao.fabricioveronez.com
